### ISSUE TITLE
Segfault in Get next line

### ISSUE THREAD

**Issue by f0rkr** [solaldunckel/get_next_line#1]
declaring the buff[BUFFER_SIZE + 1] in the stack will give you an error when I pass the BUFFER_SIZE more than the max of the stack.

**Comment by solaldunckel** [comment]
I guess that is a normal behaviour ?

**Comment by f0rkr** [comment]
I don't think so !! because it should be working with 10MB which is greater than the max of the stack
<img width="600" alt="Screen Shot 2019-10-28 at 12 01 16 PM" src="https://user-images.githubusercontent.com/39636110/67673882-69a18f00-f97b-11e9-8df1-fc88c01df94f.png">

**Comment by solaldunckel** [comment]
I'm not sure because initialising an array of BUFFER_SIZE that big segfaults the program instantly. It should work if your array is static. Some people I work with passed GNL through moulinette like this.

**Comment by f0rkr** [comment]
Check this
[get_next_line.zip](https://github.com/solaldunckel/get_next_line/files/3779608/get_next_line.zip)
